name = "SuperLU_Base"
uuid = "79fc8b2a-9fec-41f5-a0c4-660a4203283a"
authors = ["Raye Kimmerer <kimmerer@mit.edu>"]
version = "1.0.0-DEV"

[deps]
SparseBase = "8047a082-0763-4c4f-a23b-a4a948721f1d"

[compat]
julia = "1.9"
SparseBase = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
