# common structs between int32 and int64:
# generated by Clang and hand edited.
module Common
export yes_no_t, fact_t, rowperm_t, colperm_t,
trans_t, DiagScale_t, IterRefine_t, MemType,
stack_end_t, LU_space_t, norm_t, milu_t, rule_t,
PhaseType, Stype_t, Mtype_t, Dtype_t

export 
SuperMatrix,
NCformat,
NRformat,
SCformat,
SCPformat,
NCPformat,
DNformat,
NRformat_loc,
NRformat_loc3d,
SuperLUStat_t,
etree_node,
superlu_pair,
local_l_blk_info_t,
local_u_blk_info_t,
perm_array_t,
d2Hreduce_t,
treeList_t,
xtrsTimer_t,
commRequests_t,
factStat_t,
msgs_t,
factNodelists_t,
uPanelInfo_t,
lPanelInfo_t,
packLUInfo_t,
sScalePermstruct_t,
sLocalLU_t,
sLUstruct_t,
psgsmv_comm_t,
sSOLVEstruct_t,
sLUValSubBuf_t,
strf3Dpartition_t,
sscuBufs_t,
sdiagFactBufs_t,
superlu_dist_mem_usage_t,
gridinfo3d_t,
Glu_freeable_t,
superlu_scope_t,
gridinfo_t,
gEtreeInfo_t,
treeTopoInfo_t,
sForest_t,
dtrf3Dpartition_t,
dscuBufs_t,
ddiagFactBufs_t,
SuperLU_LU_stack_t,
SCT_t,
Pslu_freeable_t,
Llu_symbfact_t,
vtcsInfo_symbfact_t,
matrix_symbfact_t,
comm_symbfact_t,
psymbfact_stat_t,
dScalePermstruct_t,
Ucb_indptr_t,
dLocalLU_t,
Glu_persist_t,
dLUstruct_t,
pdgsmv_comm_t,
pxgstrs_comm_t,
dSOLVEstruct_t,
dLUValSubBuf_t,
Remain_info_t,
Ublock_info_t,
HyP_t,
e_node,
doublecomplex,
zScalePermstruct_t,
zLocalLU_t,
zLUstruct_t,
pzgsmv_comm_t,
zSOLVEstruct_t,
zLUValSubBuf_t,
ztrf3Dpartition_t,
zscuBufs_t,
zdiagFactBufs_t,
superlu_dist_options_t

@enum yes_no_t::UInt32 begin
    NO = 0
    YES = 1
end

@enum fact_t::UInt32 begin
    DOFACT = 0
    SamePattern = 1
    SamePattern_SameRowPerm = 2
    FACTORED = 3
end

@enum rowperm_t::UInt32 begin
    NOROWPERM = 0
    LargeDiag_MC64 = 1
    LargeDiag_HWPM = 2
    MY_PERMR = 3
end

@enum colperm_t::UInt32 begin
    NATURAL = 0
    MMD_ATA = 1
    MMD_AT_PLUS_A = 2
    COLAMD = 3
    METIS_AT_PLUS_A = 4
    PARMETIS = 5
    ZOLTAN = 6
    MY_PERMC = 7
end

@enum trans_t::UInt32 begin
    NOTRANS = 0
    TRANS = 1
    CONJ = 2
end

@enum DiagScale_t::UInt32 begin
    NOEQUIL = 0
    ROW = 1
    COL = 2
    BOTH = 3
end

@enum IterRefine_t::UInt32 begin
    NOREFINE = 0
    SLU_SINGLE = 1
    SLU_DOUBLE = 2
    SLU_EXTRA = 3
end

@enum MemType::UInt32 begin
    USUB = 0
    LSUB = 1
    UCOL = 2
    LUSUP = 3
    LLVL = 4
    ULVL = 5
    NO_MEMTYPE = 6
end

@enum stack_end_t::UInt32 begin
    HEAD = 0
    TAIL = 1
end

@enum LU_space_t::UInt32 begin
    SYSTEM = 0
    USER = 1
end

@enum norm_t::UInt32 begin
    ONE_NORM = 0
    TWO_NORM = 1
    INF_NORM = 2
end

@enum milu_t::UInt32 begin
    SILU = 0
    SMILU_1 = 1
    SMILU_2 = 2
    SMILU_3 = 3
end

@enum rule_t::UInt32 begin
    NODROP = 0
    DROP_BASIC = 1
    DROP_PROWS = 2
    DROP_COLUMN = 4
    DROP_AREA = 8
    DROP_SECONDARY = 14
    DROP_DYNAMIC = 16
    DROP_INTERP = 256
end

@enum PhaseType::UInt32 begin
    COLPERM = 0
    ROWPERM = 1
    RELAX = 2
    ETREE = 3
    EQUIL = 4
    SYMBFAC = 5
    DIST = 6
    FACT = 7
    COMM = 8
    COMM_DIAG = 9
    COMM_RIGHT = 10
    COMM_DOWN = 11
    SOL_COMM = 12
    SOL_GEMM = 13
    SOL_TRSM = 14
    SOL_TOT = 15
    RCOND = 16
    SOLVE = 17
    REFINE = 18
    TRSV = 19
    GEMV = 20
    FERR = 21
    NPHASES = 22
end

@enum Stype_t::UInt32 begin
    SLU_NC = 0
    SLU_NCP = 1
    SLU_NR = 2
    SLU_SC = 3
    SLU_SCP = 4
    SLU_SR = 5
    SLU_DN = 6
    SLU_NR_loc = 7
end

@enum Dtype_t::UInt32 begin
    SLU_S = 0
    SLU_D = 1
    SLU_C = 2
    SLU_Z = 3
end

@enum Mtype_t::UInt32 begin
    SLU_GE = 0
    SLU_TRLU = 1
    SLU_TRUU = 2
    SLU_TRL = 3
    SLU_TRU = 4
    SLU_SYL = 5
    SLU_SYU = 6
    SLU_HEL = 7
    SLU_HEU = 8
end
struct SuperMatrix{I}
    Stype::Stype_t
    Dtype::Dtype_t
    Mtype::Mtype_t
    nrow::I
    ncol::I
    Store::Ptr{Cvoid}
end
Base.size(A::SuperMatrix) = (A.nrow, A.ncol)
Base.size(A::SuperMatrix, dim) = size(A)[dim]

abstract type AbstractSuperLUFormat{Ti} end

struct NCformat{I} <: AbstractSuperLUFormat{I}
    nnz::I
    nzval::Ptr{Cvoid}
    rowind::Ptr{I}
    colptr::Ptr{I}
end

struct NRformat{I} <: AbstractSuperLUFormat{I}
    nnz::I
    nzval::Ptr{Cvoid}
    colind::Ptr{I}
    rowptr::Ptr{I}
end

struct SCformat{I} <: AbstractSuperLUFormat{I}
    nnz::I
    nsuper::I
    nzval::Ptr{Cvoid}
    nzval_colptr::Ptr{I}
    rowind::Ptr{I}
    rowind_colptr::Ptr{I}
    col_to_sup::Ptr{I}
    sup_to_col::Ptr{I}
end

struct SCPformat{I} <: AbstractSuperLUFormat{I}
    nnz::I
    nsuper::I
    nzval::Ptr{Cvoid}
    nzval_colbeg::Ptr{I}
    nzval_colend::Ptr{I}
    rowind::Ptr{I}
    rowind_colbeg::Ptr{I}
    rowind_colend::Ptr{I}
    col_to_sup::Ptr{I}
    sup_to_colbeg::Ptr{I}
    sup_to_colend::Ptr{I}
end

struct NCPformat{I} <: AbstractSuperLUFormat{I}
    nnz::I
    nzval::Ptr{Cvoid}
    rowind::Ptr{I}
    colbeg::Ptr{I}
    colend::Ptr{I}
end

struct DNformat{I} <: AbstractSuperLUFormat{I}
    lda::I
    nzval::Ptr{Cvoid}
end

struct NRformat_loc{I} <: AbstractSuperLUFormat{I}
    nnz_loc::I
    m_loc::I
    fst_row::I
    nzval::Ptr{Cvoid}
    rowptr::Ptr{I}
    colind::Ptr{I}
end

struct NRformat_loc3d{I} <: AbstractSuperLUFormat{I}
    A_nfmt::Ptr{NRformat_loc{I}}
    B3d::Ptr{Cvoid}
    ldb::Cint
    nrhs::Cint
    m_loc::Cint
    B2d::Ptr{Cvoid}
    row_counts_int::Ptr{Cint}
    row_disp::Ptr{Cint}
    nnz_counts_int::Ptr{Cint}
    nnz_disp::Ptr{Cint}
    b_counts_int::Ptr{Cint}
    b_disp::Ptr{Cint}
    num_procs_to_send::Cint
    procs_to_send_list::Ptr{Cint}
    send_count_list::Ptr{Cint}
    num_procs_to_recv::Cint
    procs_recv_from_list::Ptr{Cint}
    recv_count_list::Ptr{Cint}
end

const flops_t = Cfloat

const Logical = Cuchar

mutable struct SuperLUStat_t{I}
    panel_histo::Ptr{Cint}
    utime::Ptr{Cdouble}
    ops::Ptr{flops_t}
    TinyPivots::Cint
    RefineSteps::Cint
    num_look_aheads::Cint
    current_buffer::Cfloat
    peak_buffer::Cfloat
    gpu_buffer::Cfloat
    MaxActiveBTrees::I
    MaxActiveRTrees::I
end

struct Remain_info_t{I}
    lptr::I
    ib::I
    eo::I
    nrows::I
    FullRow::I
    StRow::I
end

struct Ublock_info_t{I}
    rukp::I
    iukp::I
    jb::I
    full_u_cols::I
    eo::I
    ncols::I
    StCol::I
end

struct etree_node
    id::Cint
    key::Cint
    next::Ptr{Cvoid}
end

struct superlu_pair
    ind::Cint
    val::Cint
end

struct local_l_blk_info_t{I}
    luptrj::I
    lptrj::I
    lib::I
end

struct local_u_blk_info_t{I}
    iuip::I
    ruip::I
    ljb::I
end

struct perm_array_t{I}
    perm_c_supno::Ptr{I}
    iperm_c_supno::Ptr{I}
end

struct d2Hreduce_t{I}
    next_col::I
    next_k::I
    kljb::I
    kijb::I
    copyL_kljb::I
    copyU_kljb::I
    l_copy_len::I
    u_copy_len::I
    kindexL::Ptr{I}
    kindexU::Ptr{I}
    mkrow::I
    mkcol::I
    ksup_size::I
end

struct treeList_t{I}
    numChild::I
    numDescendents::I
    left::I
    right::I
    extra::I
    childrenList::Ptr{I}
    depth::I
    weight::Cdouble
    iWeight::Cdouble
    scuWeight::Cdouble
end

@enum treePartStrat::UInt32 begin
    ND = 0
    GD = 1
end

struct xtrsTimer_t{I}
    trsDataSendXY::Cdouble
    trsDataSendZ::Cdouble
    trsDataRecvXY::Cdouble
    trsDataRecvZ::Cdouble
    t_pdReDistribute_X_to_B::Cdouble
    t_pdReDistribute_B_to_X::Cdouble
    t_forwardSolve::Cdouble
    tfs_compute::Cdouble
    tfs_comm::Cdouble
    t_backwardSolve::Cdouble
    tbs_compute::Cdouble
    tbs_comm::Cdouble
    tbs_tree::NTuple{64, Cdouble}
    tfs_tree::NTuple{64, Cdouble}
    trsMsgSentXY::I
    trsMsgSentZ::I
    trsMsgRecvXY::I
    trsMsgRecvZ::I
    ppXmem::Cdouble
end

struct factStat_t{I}
    factored::Ptr{I}
    factored_D::Ptr{I}
    factored_L::Ptr{I}
    factored_U::Ptr{I}
    IrecvPlcd_D::Ptr{I}
    IbcastPanel_L::Ptr{I}
    IbcastPanel_U::Ptr{I}
    numChildLeft::Ptr{I}
    gpuLUreduced::Ptr{I}
end

struct msgs_t
    msgcnt::Ptr{Cint}
    msgcntU::Ptr{Cint}
end

struct factNodelists_t{I}
    iperm_c_supno::Ptr{I}
    iperm_u::Ptr{I}
    perm_u::Ptr{I}
    indirect::Ptr{Cint}
    indirect2::Ptr{Cint}
end

struct uPanelInfo_t{I}
    nub::I
    klst::I
    ldu::I
    usub::Ptr{I}
end

struct lPanelInfo_t{I}
    lsub::Ptr{I}
    lusup::Ptr{Cvoid}
    luptr0::I
    nlb::I
    nsupr::I
end

struct packLUInfo_t{I}
    Ublock_info::Ptr{Ublock_info_t{I}}
    Remain_info::Ptr{Remain_info_t{I}}
    uPanelInfo::Ptr{uPanelInfo_t{I}}
    lPanelInfo::Ptr{lPanelInfo_t{I}}
end

mutable struct sScalePermstruct_t{I}
    DiagScale::DiagScale_t
    R::Ptr{Cfloat}
    C::Ptr{Cfloat}
    perm_r::Ptr{I}
    perm_c::Ptr{I}
end

struct Ucb_indptr_t{I}
    lbnum::I
    indpos::I
end

struct sLocalLU_t{I}
    Lrowind_bc_ptr::Ptr{Ptr{I}}
    Lrowind_bc_dat::Ptr{I}
    Lrowind_bc_offset::Ptr{Clong}
    Lrowind_bc_cnt::Clong
    Lnzval_bc_ptr::Ptr{Ptr{Cfloat}}
    Lnzval_bc_dat::Ptr{Cfloat}
    Lnzval_bc_offset::Ptr{Clong}
    Lnzval_bc_cnt::Clong
    Linv_bc_ptr::Ptr{Ptr{Cfloat}}
    Linv_bc_dat::Ptr{Cfloat}
    Linv_bc_offset::Ptr{Clong}
    Linv_bc_cnt::Clong
    Lindval_loc_bc_ptr::Ptr{Ptr{I}}
    Lindval_loc_bc_dat::Ptr{I}
    Lindval_loc_bc_offset::Ptr{Clong}
    Lindval_loc_bc_cnt::Clong
    Unnz::Ptr{I}
    Lrowind_bc_2_lsum::Ptr{Ptr{I}}
    Uinv_bc_ptr::Ptr{Ptr{Cfloat}}
    Uinv_bc_dat::Ptr{Cfloat}
    Uinv_bc_offset::Ptr{Clong}
    Uinv_bc_cnt::Clong
    Ufstnz_br_ptr::Ptr{Ptr{I}}
    Ufstnz_br_dat::Ptr{I}
    Ufstnz_br_offset::Ptr{Clong}
    Ufstnz_br_cnt::Clong
    Unzval_br_ptr::Ptr{Ptr{Cfloat}}
    Unzval_br_dat::Ptr{Cfloat}
    Unzval_br_offset::Ptr{Clong}
    Unzval_br_cnt::Clong
    LBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    LRtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    UBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    URtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    Lsub_buf_2::NTuple{50, Ptr{I}}
    Lval_buf_2::NTuple{50, Ptr{Cfloat}}
    Usub_buf_2::NTuple{50, Ptr{I}}
    Uval_buf_2::NTuple{50, Ptr{Cfloat}}
    ujrow::Ptr{Cfloat}
    bufmax::NTuple{5, I}
    ToRecv::Ptr{Cint}
    ToSendD::Ptr{Cint}
    ToSendR::Ptr{Ptr{Cint}}
    fmod::Ptr{Cint}
    fsendx_plist::Ptr{Ptr{Cint}}
    frecv::Ptr{Cint}
    nfrecvx::Cint
    nfsendx::Cint
    bmod::Ptr{Cint}
    bsendx_plist::Ptr{Ptr{Cint}}
    brecv::Ptr{Cint}
    nbrecvx::Cint
    nbsendx::Cint
    mod_bit::Ptr{Cint}
    ilsum::Ptr{I}
    ldalsum::I
    SolveMsgSent::I
    SolveMsgVol::I
    UT_SOLVE::I
    L_SOLVE::I
    FRECV::I
    ut_ldalsum::I
    ut_ilsum::Ptr{I}
    utmod::Ptr{I}
    ut_sendx_plist::Ptr{Ptr{I}}
    utrecv::Ptr{I}
    n_utsendx::I
    n_utrecvx::I
    n_utrecvmod::I
    nroot::I
    ut_modbit::Ptr{I}
    Urbs::Ptr{I}
    Ucb_indptr::Ptr{Ptr{Ucb_indptr_t{I}}}
    Ucb_inddat::Ptr{Ucb_indptr_t{I}}
    Ucb_indoffset::Ptr{Clong}
    Ucb_indcnt::Clong
    Ucb_valptr::Ptr{Ptr{I}}
    Ucb_valdat::Ptr{I}
    Ucb_valoffset::Ptr{Clong}
    Ucb_valcnt::Clong
    n::I
    nleaf::I
    nfrecvmod::I
    inv::I
end

struct Glu_persist_t{I}
    xsup::Ptr{I}
    supno::Ptr{I}
end

mutable struct sLUstruct_t{I}
    etree::Ptr{I}
    Glu_persist::Ptr{Glu_persist_t{I}}
    Llu::Ptr{sLocalLU_t{I}}
    dt::Cchar
end

struct psgsmv_comm_t{I}
    extern_start::Ptr{I}
    ind_tosend::Ptr{I}
    ind_torecv::Ptr{I}
    ptr_ind_tosend::Ptr{I}
    ptr_ind_torecv::Ptr{I}
    SendCounts::Ptr{Cint}
    RecvCounts::Ptr{Cint}
    val_tosend::Ptr{Cvoid}
    val_torecv::Ptr{Cvoid}
    TotalIndSend::I
    TotalValSend::I
end

struct pxgstrs_comm_t{I}
    B_to_X_SendCnt::Ptr{Cint}
    X_to_B_SendCnt::Ptr{Cint}
    ptr_to_ibuf::Ptr{Cint}
    ptr_to_dbuf::Ptr{Cint}
    X_to_B_iSendCnt::Ptr{Cint}
    X_to_B_vSendCnt::Ptr{Cint}
    disp_ibuf::Ptr{Cint}
    send_ibuf::Ptr{I}
    send_dbuf::Ptr{Cvoid}
    x2b::I
    b2x::I
    send_ibuf2::Ptr{I}
    recv_ibuf2::Ptr{I}
    send_dbuf2::Ptr{Cvoid}
    recv_dbuf2::Ptr{Cvoid}
end

mutable struct sSOLVEstruct_t{I}
    row_to_proc::Ptr{I}
    inv_perm_c::Ptr{I}
    num_diag_procs::I
    diag_procs::Ptr{I}
    diag_len::Ptr{I}
    gsmv_comm::Ptr{psgsmv_comm_t{I}}
    gstrs_comm::Ptr{pxgstrs_comm_t{I}}
    A_colind_gsmv::Ptr{I}
    xrow_to_proc::Ptr{I}
    A3d::Ptr{NRformat_loc3d{I}}
end

struct sLUValSubBuf_t{I}
    Lsub_buf::Ptr{I}
    Lval_buf::Ptr{Cfloat}
    Usub_buf::Ptr{I}
    Uval_buf::Ptr{Cfloat}
end

struct gEtreeInfo_t{I}
    setree::Ptr{I}
    numChildLeft::Ptr{I}
end

struct treeTopoInfo_t{I}
    numLvl::I
    eTreeTopLims::Ptr{I}
    myIperm::Ptr{I}
end

struct sForest_t{I}
    nNodes::I
    nodeList::Ptr{I}
    numLvl::I
    numTrees::I
    topoInfo::treeTopoInfo_t{I}
    weight::Cdouble
    cost::Cdouble
end

struct strf3Dpartition_t{I}
    gEtreeInfo::gEtreeInfo_t{I}
    iperm_c_supno::Ptr{I}
    myNodeCount::Ptr{I}
    myTreeIdxs::Ptr{I}
    myZeroTrIdxs::Ptr{I}
    treePerm::Ptr{Ptr{I}}
    sForests::Ptr{Ptr{sForest_t{I}}}
    supernode2treeMap::Ptr{I}
    LUvsb::Ptr{sLUValSubBuf_t{I}}
end

struct sscuBufs_t
    bigU::Ptr{Cfloat}
    bigV::Ptr{Cfloat}
end

struct sdiagFactBufs_t
    BlockLFactor::Ptr{Cfloat}
    BlockUFactor::Ptr{Cfloat}
end

struct superlu_dist_mem_usage_t
    for_lu::Cfloat
    total::Cfloat
    expansions::Cint
    nnzL::Int64
    nnzU::Int64
end

Base.@kwdef mutable struct superlu_dist_options_t
    Fact::fact_t  = DOFACT
    Equil::yes_no_t  = YES
    DiagInv::yes_no_t  = NO
    ColPerm::colperm_t  = Sys.iswindows() ? METIS_AT_PLUS_A : MMD_AT_PLUS_A
    Trans::trans_t  = NOTRANS
    IterRefine::IterRefine_t  = SLU_DOUBLE
    DiagPivotThresh::Cdouble  = 0
    SymmetricMode::yes_no_t  = NO
    PivotGrowth::yes_no_t  = NO
    ConditionNumber::yes_no_t  = NO
    RowPerm::rowperm_t  = LargeDiag_MC64
    ILU_DropRule::Cint  = 1
    ILU_DropTol::Cdouble  = 0
    ILU_FillFactor::Cdouble  = 0
    ILU_Norm::norm_t  = ONE_NORM
    ILU_FillTol::Cdouble  = 0
    ILU_MILU::milu_t  = SILU
    ILU_MILU_Dim::Cdouble  = 0
    ParSymbFact::yes_no_t  = NO
    ReplaceTinyPivot::yes_no_t  = NO
    SolveInitialized::yes_no_t  = NO
    RefineInitialized::yes_no_t  = NO
    PrintStat::yes_no_t  = YES
    lookahead_etree::yes_no_t  = NO
    num_lookaheads::Cint  = 10
    superlu_relax::Cint  = 60
    superlu_maxsup::Cint  = 256
    superlu_rankorder::NTuple{4, Cchar} = ('Z', '\0', '\0', '\0') #???
    superlu_lbs::NTuple{4, Cchar} = ('G', 'D', '\0', '\0') #???
    superlu_n_gemm::Cint  = 5000
    superlu_max_buffer_size::Cint  = 256000000
    superlu_num_gpu_streams::Cint  = 8
    superlu_acc_offload::Cint  = 1
    SymPattern::yes_no_t  = NO
    Use_TensorCore::yes_no_t  = NO
    Algo3d::yes_no_t   = NO
end

struct Glu_freeable_t{I}
    lsub::Ptr{I}
    xlsub::Ptr{I}
    usub::Ptr{I}
    xusub::Ptr{I}
    nzlmax::I
    nzumax::I
    MemModel::LU_space_t
    nnzLU::Int64
end

struct dLUValSubBuf_t{I}
    Lsub_buf::Ptr{I}
    Lval_buf::Ptr{Cdouble}
    Usub_buf::Ptr{I}
    Uval_buf::Ptr{Cdouble}
end

struct dtrf3Dpartition_t{I}
    gEtreeInfo::gEtreeInfo_t{I}
    iperm_c_supno::Ptr{I}
    myNodeCount::Ptr{I}
    myTreeIdxs::Ptr{I}
    myZeroTrIdxs::Ptr{I}
    treePerm::Ptr{Ptr{I}}
    sForests::Ptr{Ptr{sForest_t{I}}}
    supernode2treeMap::Ptr{I}
    LUvsb::Ptr{dLUValSubBuf_t{I}}
end

struct dscuBufs_t{I}
    bigU::Ptr{Cdouble}
    bigV::Ptr{Cdouble}
end

struct ddiagFactBufs_t
    BlockLFactor::Ptr{Cdouble}
    BlockUFactor::Ptr{Cdouble}
end

struct SuperLU_LU_stack_t
    size::Cint
    used::Cint
    top1::Cint
    top2::Cint
    array::Ptr{Cvoid}
end

struct SCT_t{I}
    datatransfer_count::I
    schurPhiCallCount::I
    PhiMemCpyCounter::I
    acc_load_imbal::Cdouble
    LookAheadGEMMFlOp::Cdouble
    PhiWaitTimer_2::Cdouble
    LookAheadGEMMTimer::Cdouble
    LookAheadRowSepTimer::Cdouble
    LookAheadScatterTimer::Cdouble
    GatherTimer::Cdouble
    GatherMOP::Cdouble
    scatter_mem_op_counter::Cdouble
    LookAheadRowSepMOP::Cdouble
    scatter_mem_op_timer::Cdouble
    schur_flop_counter::Cdouble
    schur_flop_timer::Cdouble
    CPUOffloadTimer::Cdouble
    PhiWaitTimer::Cdouble
    NetSchurUpTimer::Cdouble
    AssemblyTimer::Cdouble
    PhiMemCpyTimer::Cdouble
    datatransfer_timer::Cdouble
    LookAheadScatterMOP::Cdouble
    schurPhiCallTimer::Cdouble
    autotunetime::Cdouble
    Predicted_acc_sch_time::Ptr{Cdouble}
    Predicted_acc_gemm_time::Ptr{Cdouble}
    Predicted_acc_scatter_time::Ptr{Cdouble}
    trf2_flops::Cdouble
    trf2_time::Cdouble
    offloadable_flops::Cdouble
    offloadable_mops::Cdouble
    SchurCompUdtThreadTime::Ptr{Cdouble}
    Predicted_host_sch_time::Ptr{Cdouble}
    Measured_host_sch_time::Ptr{Cdouble}
    pdgstrs2_timer::Cdouble
    pdgstrf2_timer::Cdouble
    lookaheadupdatetimer::Cdouble
    pdgstrfTimer::Cdouble
    Local_Dgstrf2_Thread_tl::Ptr{Cdouble}
    Wait_UDiagBlock_Recv_tl::Cdouble
    Wait_LDiagBlock_Recv_tl::Cdouble
    Recv_UDiagBlock_tl::Cdouble
    Wait_UDiagBlockSend_tl::Cdouble
    L_PanelUpdate_tl::Cdouble
    Bcast_UPanel_tl::Cdouble
    Bcast_LPanel_tl::Cdouble
    Wait_LSend_tl::Cdouble
    Wait_USend_tl::Cdouble
    Wait_URecv_tl::Cdouble
    Wait_LRecv_tl::Cdouble
    GetAijLock_Thread_tl::Ptr{Cdouble}
    PDGSTRS2_tl::Cdouble
    Phase_Factor_tl::Cdouble
    Phase_LU_Update_tl::Cdouble
    Phase_SC_Update_tl::Cdouble
    ancsReduce::Cdouble
    gatherLUtimer::Cdouble
    tFactor3D::NTuple{32, Cdouble}
    tSchCompUdt3d::NTuple{32, Cdouble}
    tAsyncPipeTail::Cdouble
    tStartup::Cdouble
    commVolFactor::Cdouble
    commVolRed::Cdouble
end

struct Pslu_freeable_t{I}
    xlsub::Ptr{I}
    lsub::Ptr{I}
    szLsub::I
    xusub::Ptr{I}
    usub::Ptr{I}
    szUsub::I
    supno_loc::Ptr{I}
    xsup_beg_loc::Ptr{I}
    xsup_end_loc::Ptr{I}
    nvtcs_loc::I
    globToLoc::Ptr{I}
    maxNvtcsPProc::I
    nnzLU::Int64
end

struct Llu_symbfact_t{I}
    xlsubPr::Ptr{I}
    lsubPr::Ptr{I}
    szLsubPr::I
    indLsubPr::I
    xusubPr::Ptr{I}
    usubPr::Ptr{I}
    szUsubPr::I
    indUsubPr::I
    xlsub_rcvd::Ptr{I}
    xlsub::Ptr{I}
    lsub::Ptr{I}
    szLsub::I
    nextl::I
    xusub_rcvd::Ptr{I}
    xusub::Ptr{I}
    usub::Ptr{I}
    szUsub::I
    nextu::I
    cntelt_vtcs::Ptr{I}
    cntelt_vtcsA_lvl::Ptr{I}
    MemModel::LU_space_t
    no_expand::I
    no_expand_pr::I
    no_expcp::I
end

struct vtcsInfo_symbfact_t{I}
    maxSzBlk::I
    maxNvtcsNds_loc::I
    maxNeltsVtx::I
    nblks_loc::I
    begEndBlks_loc::Ptr{I}
    curblk_loc::I
    nvtcs_loc::I
    nvtcsLvl_loc::I
    filledSep::Cint
    nnz_asup_loc::I
    nnz_ainf_loc::I
    xusub_nextLvl::I
    xlsub_nextLvl::I
    fstVtx_nextLvl::I
end

struct matrix_symbfact_t{I}
    x_ainf::Ptr{I}
    ind_ainf::Ptr{I}
    x_asup::Ptr{I}
    ind_asup::Ptr{I}
end

struct comm_symbfact_t{I}
    rcv_interLvl::Ptr{I}
    snd_interLvl::Ptr{I}
    snd_interSz::Ptr{I}
    snd_LinterSz::Ptr{I}
    snd_vtxinter::Ptr{I}
    snd_intraLvl::Ptr{I}
    snd_intraSz::I
    snd_LintraSz::I
    rcv_intraLvl::Ptr{I}
    rcv_buf::Ptr{I}
    rcv_bufSz::I
    snd_buf::Ptr{I}
    snd_bufSz::I
    ptr_rcvBuf::Ptr{I}
end

struct psymbfact_stat_t{I}
    fill_par::I
    relax_seps::Cfloat
    relax_curSep::Cfloat
    relax_gen::Cfloat
    nops::Cfloat
    nDnsCurSep::I
    nDnsUpSeps::I
    no_shmSnd::Cfloat
    no_msgsSnd::Cfloat
    maxsz_msgSnd::I
    sz_msgsSnd::Cfloat
    no_shmRcvd::Cfloat
    no_msgsRcvd::Cfloat
    maxsz_msgRcvd::I
    sz_msgsRcvd::Cfloat
    no_msgsCol::Cfloat
    maxsz_msgCol::I
    sz_msgsCol::Cfloat
    fill_pelt::NTuple{6, Cfloat}
    estimLSz::I
    estimUSz::I
    maxSzLPr::I
    maxSzUPr::I
    maxSzBuf::I
    szDnsSep::I
    allocMem::Cfloat
end

mutable struct dScalePermstruct_t{I}
    DiagScale::DiagScale_t
    R::Ptr{Cdouble}
    C::Ptr{Cdouble}
    perm_r::Ptr{I}
    perm_c::Ptr{I}
end

struct dLocalLU_t{I}
    Lrowind_bc_ptr::Ptr{Ptr{I}}
    Lrowind_bc_dat::Ptr{I}
    Lrowind_bc_offset::Ptr{Clong}
    Lrowind_bc_cnt::Clong
    Lnzval_bc_ptr::Ptr{Ptr{Cdouble}}
    Lnzval_bc_dat::Ptr{Cdouble}
    Lnzval_bc_offset::Ptr{Clong}
    Lnzval_bc_cnt::Clong
    Linv_bc_ptr::Ptr{Ptr{Cdouble}}
    Linv_bc_dat::Ptr{Cdouble}
    Linv_bc_offset::Ptr{Clong}
    Linv_bc_cnt::Clong
    Lindval_loc_bc_ptr::Ptr{Ptr{I}}
    Lindval_loc_bc_dat::Ptr{I}
    Lindval_loc_bc_offset::Ptr{Clong}
    Lindval_loc_bc_cnt::Clong
    Ucolind_bc_ptr::Ptr{Ptr{I}}
    Ucolind_bc_dat::Ptr{I}
    Ucolind_bc_offset::Ptr{Int64}
    Ucolind_bc_cnt::Int64
    Unzval_bc_ptr::Ptr{Ptr{Cdouble}}
    Unzval_bc_dat::Ptr{Cdouble}
    Unzval_bc_offset::Ptr{Int64}
    Unzval_bc_cnt::Int64
    Uindval_loc_bc_ptr::Ptr{Ptr{I}}
    Uindval_loc_bc_dat::Ptr{I}
    Uindval_loc_bc_offset::Ptr{Int64}
    Uindval_loc_bc_cnt::Int64
    Unnz::Ptr{I}
    Lrowind_bc_2_lsum::Ptr{Ptr{I}}
    Uinv_bc_ptr::Ptr{Ptr{Cdouble}}
    Uinv_bc_dat::Ptr{Cdouble}
    Uinv_bc_offset::Ptr{Clong}
    Uinv_bc_cnt::Clong
    Ufstnz_br_ptr::Ptr{Ptr{I}}
    Ufstnz_br_dat::Ptr{I}
    Ufstnz_br_offset::Ptr{Clong}
    Ufstnz_br_cnt::Clong
    Unzval_br_ptr::Ptr{Ptr{Cdouble}}
    Unzval_br_dat::Ptr{Cdouble}
    Unzval_br_offset::Ptr{Clong}
    Unzval_br_cnt::Clong
    LBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    LRtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    UBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    URtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    Lsub_buf_2::NTuple{50, Ptr{I}}
    Lval_buf_2::NTuple{50, Ptr{Cdouble}}
    Usub_buf_2::NTuple{50, Ptr{I}}
    Uval_buf_2::NTuple{50, Ptr{Cdouble}}
    ujrow::Ptr{Cdouble}
    bufmax::NTuple{5, I}
    ToRecv::Ptr{Cint}
    ToSendD::Ptr{Cint}
    ToSendR::Ptr{Ptr{Cint}}
    fmod::Ptr{Cint}
    fsendx_plist::Ptr{Ptr{Cint}}
    frecv::Ptr{Cint}
    nfrecvx::Cint
    nfsendx::Cint
    bmod::Ptr{Cint}
    bsendx_plist::Ptr{Ptr{Cint}}
    brecv::Ptr{Cint}
    nbrecvx::Cint
    nbsendx::Cint
    mod_bit::Ptr{Cint}
    ilsum::Ptr{I}
    ldalsum::I
    SolveMsgSent::I
    SolveMsgVol::I
    UT_SOLVE::I
    L_SOLVE::I
    FRECV::I
    ut_ldalsum::I
    ut_ilsum::Ptr{I}
    utmod::Ptr{I}
    ut_sendx_plist::Ptr{Ptr{I}}
    utrecv::Ptr{I}
    n_utsendx::I
    n_utrecvx::I
    n_utrecvmod::I
    nroot::I
    ut_modbit::Ptr{I}
    Urbs::Ptr{I}
    Ucb_indptr::Ptr{Ptr{Ucb_indptr_t{I}}}
    Ucb_inddat::Ptr{Ucb_indptr_t{I}}
    Ucb_indoffset::Ptr{Clong}
    Ucb_indcnt::Clong
    Ucb_valptr::Ptr{Ptr{I}}
    Ucb_valdat::Ptr{I}
    Ucb_valoffset::Ptr{Clong}
    Ucb_valcnt::Clong
    n::I
    nleaf::I
    nfrecvmod::I
    inv::I
end

mutable struct dLUstruct_t{I}
    etree::Ptr{I}
    Glu_persist::Ptr{Glu_persist_t{I}}
    Llu::Ptr{dLocalLU_t{I}}
    dt::Cchar
end

struct pdgsmv_comm_t{I}
    extern_start::Ptr{I}
    ind_tosend::Ptr{I}
    ind_torecv::Ptr{I}
    ptr_ind_tosend::Ptr{I}
    ptr_ind_torecv::Ptr{I}
    SendCounts::Ptr{Cint}
    RecvCounts::Ptr{Cint}
    val_tosend::Ptr{Cdouble}
    val_torecv::Ptr{Cdouble}
    TotalIndSend::I
    TotalValSend::I
end

mutable struct dSOLVEstruct_t{I}
    row_to_proc::Ptr{I}
    inv_perm_c::Ptr{I}
    num_diag_procs::I
    diag_procs::Ptr{I}
    diag_len::Ptr{I}
    gsmv_comm::Ptr{pdgsmv_comm_t{I}}
    gstrs_comm::Ptr{pxgstrs_comm_t{I}}
    A_colind_gsmv::Ptr{I}
    xrow_to_proc::Ptr{I}
    A3d::Ptr{NRformat_loc3d{I}}
end

struct HyP_t{I}
    lookAhead_info::Ptr{Remain_info_t{I}}
    Remain_info::Ptr{Remain_info_t{I}}
    Ublock_info::Ptr{Ublock_info_t{I}}
    Ublock_info_Phi::Ptr{Ublock_info_t{I}}
    first_l_block_acc::I
    first_u_block_acc::I
    last_offload::I
    Lblock_dirty_bit::Ptr{I}
    Ublock_dirty_bit::Ptr{I}
    lookAhead_L_buff::Ptr{Cvoid}
    Remain_L_buff::Ptr{Cvoid}
    lookAheadBlk::I
    RemainBlk::I
    num_look_aheads::I
    nsupers::I
    ldu::I
    ldu_Phi::I
    num_u_blks::I
    num_u_blks_Phi::I
    jj_cpu::I
    bigU_Phi::Ptr{Cvoid}
    bigU_host::Ptr{Cvoid}
    Lnbrow::I
    Rnbrow::I
    buffer_size::I
    bigu_size::I
    offloadCondition::Cint
    superlu_acc_offload::Cint
    nGPUStreams::Cint
end

struct e_node
    size::Cint
    mem::Ptr{Cvoid}
end

const SuperLU_ExpHeader = e_node

struct doublecomplex
    r::Cdouble
    i::Cdouble
end
mutable struct zScalePermstruct_t{I}
    DiagScale::DiagScale_t
    R::Ptr{Cdouble}
    C::Ptr{Cdouble}
    perm_r::Ptr{I}
    perm_c::Ptr{I}
end

struct zLocalLU_t{I}
    Lrowind_bc_ptr::Ptr{Ptr{I}}
    Lrowind_bc_dat::Ptr{I}
    Lrowind_bc_offset::Ptr{Clong}
    Lrowind_bc_cnt::Clong
    Lnzval_bc_ptr::Ptr{Ptr{doublecomplex}}
    Lnzval_bc_dat::Ptr{doublecomplex}
    Lnzval_bc_offset::Ptr{Clong}
    Lnzval_bc_cnt::Clong
    Linv_bc_ptr::Ptr{Ptr{doublecomplex}}
    Linv_bc_dat::Ptr{doublecomplex}
    Linv_bc_offset::Ptr{Clong}
    Linv_bc_cnt::Clong
    Lindval_loc_bc_ptr::Ptr{Ptr{I}}
    Lindval_loc_bc_dat::Ptr{I}
    Lindval_loc_bc_offset::Ptr{Clong}
    Lindval_loc_bc_cnt::Clong
    Unnz::Ptr{I}
    Lrowind_bc_2_lsum::Ptr{Ptr{I}}
    Uinv_bc_ptr::Ptr{Ptr{doublecomplex}}
    Uinv_bc_dat::Ptr{doublecomplex}
    Uinv_bc_offset::Ptr{Clong}
    Uinv_bc_cnt::Clong
    Ufstnz_br_ptr::Ptr{Ptr{I}}
    Ufstnz_br_dat::Ptr{I}
    Ufstnz_br_offset::Ptr{Clong}
    Ufstnz_br_cnt::Clong
    Unzval_br_ptr::Ptr{Ptr{doublecomplex}}
    Unzval_br_dat::Ptr{doublecomplex}
    Unzval_br_offset::Ptr{Clong}
    Unzval_br_cnt::Clong
    LBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    LRtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    UBtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    URtree_ptr::Ptr{Cvoid} # C_Tree in SuperLU_DIST
    Lsub_buf_2::NTuple{50, Ptr{I}}
    Lval_buf_2::NTuple{50, Ptr{doublecomplex}}
    Usub_buf_2::NTuple{50, Ptr{I}}
    Uval_buf_2::NTuple{50, Ptr{doublecomplex}}
    ujrow::Ptr{doublecomplex}
    bufmax::NTuple{5, I}
    ToRecv::Ptr{Cint}
    ToSendD::Ptr{Cint}
    ToSendR::Ptr{Ptr{Cint}}
    fmod::Ptr{Cint}
    fsendx_plist::Ptr{Ptr{Cint}}
    frecv::Ptr{Cint}
    nfrecvx::Cint
    nfsendx::Cint
    bmod::Ptr{Cint}
    bsendx_plist::Ptr{Ptr{Cint}}
    brecv::Ptr{Cint}
    nbrecvx::Cint
    nbsendx::Cint
    mod_bit::Ptr{Cint}
    ilsum::Ptr{I}
    ldalsum::I
    SolveMsgSent::I
    SolveMsgVol::I
    UT_SOLVE::I
    L_SOLVE::I
    FRECV::I
    ut_ldalsum::I
    ut_ilsum::Ptr{I}
    utmod::Ptr{I}
    ut_sendx_plist::Ptr{Ptr{I}}
    utrecv::Ptr{I}
    n_utsendx::I
    n_utrecvx::I
    n_utrecvmod::I
    nroot::I
    ut_modbit::Ptr{I}
    Urbs::Ptr{I}
    Ucb_indptr::Ptr{Ptr{Ucb_indptr_t{I}}}
    Ucb_inddat::Ptr{Ucb_indptr_t{I}}
    Ucb_indoffset::Ptr{Clong}
    Ucb_indcnt::Clong
    Ucb_valptr::Ptr{Ptr{I}}
    Ucb_valdat::Ptr{I}
    Ucb_valoffset::Ptr{Clong}
    Ucb_valcnt::Clong
    n::I
    nleaf::I
    nfrecvmod::I
    inv::I
end

mutable struct zLUstruct_t{I}
    etree::Ptr{I}
    Glu_persist::Ptr{Glu_persist_t{I}}
    Llu::Ptr{zLocalLU_t{I}}
    dt::Cchar
end

struct pzgsmv_comm_t{I}
    extern_start::Ptr{I}
    ind_tosend::Ptr{I}
    ind_torecv::Ptr{I}
    ptr_ind_tosend::Ptr{I}
    ptr_ind_torecv::Ptr{I}
    SendCounts::Ptr{Cint}
    RecvCounts::Ptr{Cint}
    val_tosend::Ptr{doublecomplex}
    val_torecv::Ptr{doublecomplex}
    TotalIndSend::I
    TotalValSend::I
end

mutable struct zSOLVEstruct_t{I}
    row_to_proc::Ptr{I}
    inv_perm_c::Ptr{I}
    num_diag_procs::I
    diag_procs::Ptr{I}
    diag_len::Ptr{I}
    gsmv_comm::Ptr{pzgsmv_comm_t{I}}
    gstrs_comm::Ptr{pxgstrs_comm_t{I}}
    A_colind_gsmv::Ptr{I}
    xrow_to_proc::Ptr{I}
    A3d::Ptr{NRformat_loc3d}
end

struct zLUValSubBuf_t{I}
    Lsub_buf::Ptr{I}
    Lval_buf::Ptr{doublecomplex}
    Usub_buf::Ptr{I}
    Uval_buf::Ptr{doublecomplex}
end

struct ztrf3Dpartition_t{I}
    gEtreeInfo::gEtreeInfo_t{I}
    iperm_c_supno::Ptr{I}
    myNodeCount::Ptr{I}
    myTreeIdxs::Ptr{I}
    myZeroTrIdxs::Ptr{I}
    treePerm::Ptr{Ptr{I}}
    sForests::Ptr{Ptr{sForest_t{I}}}
    supernode2treeMap::Ptr{I}
    LUvsb::Ptr{zLUValSubBuf_t{I}}
end

struct zscuBufs_t
    bigU::Ptr{doublecomplex}
    bigV::Ptr{doublecomplex}
end

struct zdiagFactBufs_t
    BlockLFactor::Ptr{doublecomplex}
    BlockUFactor::Ptr{doublecomplex}
end
end
